In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.__version__

'1.23.5'

# Ndarray Object
The most important object defined in NumPy is an N-dimensional array type called **ndarray**. It describes the collection of the same type. Items in the collection can be accessed using a zero-based index.

Every item in a ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object.

In [3]:
def about_array(arr):
    print(arr)
    print('size of the array:', arr.shape)
    print('type of the elements:', arr.dtype)
    print('number of dimensions:', arr.ndim)
    print('total number of elements:', arr.size)
    print('the size in bytes of each element:', arr.itemsize)
    print('the size of the whole array:', f"{arr.size * arr.itemsize} bytes", '\n')

In [4]:
a = np.array([1, 2, 3, 4, 5])
about_array(a)

b = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
about_array(b)

[1 2 3 4 5]
size of the array: (5,)
type of the elements: int64
number of dimensions: 1
total number of elements: 5
the size in bytes of each element: 8
the size of the whole array: 40 bytes 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
size of the array: (3, 4)
type of the elements: int64
number of dimensions: 2
total number of elements: 12
the size in bytes of each element: 8
the size of the whole array: 96 bytes 



Find max and min values in array:

In [6]:
print(a)
print(np.max(a))
print(np.min(a))

[1 2 3 4 5]
5
1


In [7]:
print(b)
print(np.max(b))
print(np.max(b, axis=0))
print(np.max(b, axis=1))
print(np.min(b))
print(np.min(b, axis=0))
print(np.min(b, axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[ 9 10 11 12]
[ 4  8 12]
1
[1 2 3 4]
[1 5 9]


# Creating arrays
there are 6 general ways for creating arrays:
1. Conversion from other Python structures
2. Intrinsic NumPy array creation functions (arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk
5. Creating arrays from row bytes
6. Use of special library functions (random)

create 1-dimensional array:

In [ ]:
a = np.arange(10)
about_array(a)

create 2-dimensional array:

In [ ]:
a = np.arange(15).reshape((3, 5))
about_array(a)

create 3-dimensional array with zeros:

In [ ]:
a = np.zeros((3, 4, 5), dtype=np.int16)
about_array(a)

create 3-dimensional array with ones:

In [ ]:
a = np.ones((3, 4, 5), dtype=np.int16)
about_array(a)

create empty array:

In [ ]:
a = np.empty((2, 3))
about_array(a)

create an array of length 10 with values evenly distributed between 5 and 50:

In [ ]:
a = np.linspace(5, 50, 10)
about_array(a)

create an array of 10 fives:

In [ ]:
a = np.ones(10, dtype=np.int64) * 5
about_array(a)

In [ ]:
a = np.full((2, 3), 5)
about_array(a)

create an array of all the even integers from 10 to 100:

In [ ]:
a = np.arange(10, 101, 2)
about_array(a)

create a Vandermode matrix:

In [ ]:
x = np.array([2, 5, 9, 13])
a = np.vander(x, increasing=True)
about_array(a)

# Data Types
the most common data types in NumPy:
- int8
- int16
- int32
- int64
- float16
- float32
- float64
- complex64
- complex128

# Indexing

In [ ]:
a = np.array([[1, 2, 6], [3, 4, 8]])
print(a)
print(a.shape)

print(a[0])
print(a[:, 0])
print(a[0, :])

In [ ]:
a = np.array([10, 19, 30, 41, 50, 61])
print(a)

b = [1, 3, 5]
print(a[b])

even = np.argwhere(a%2==0).flatten()
print(a[even])

In [ ]:
x = np.linspace(0, 2 * np.pi, 10)

In [ ]:
f = np.sin(x)

In [ ]:
f

In [ ]:
a

In [ ]:
print(a)

In [ ]:
c = np.arange(60).reshape((3, 4, 5))

In [ ]:
print(c)

In [ ]:
print(np.arange(10_000))

In [ ]:
print(np.arange(10_000).reshape((100, 100)))

In [ ]:
print(np.arange(10_000).reshape((10, 10, 10, 10)))

In [ ]:
a = np.arange(1, 7)
print(a)
print(a.shape)

b = a[np.newaxis, :]
print(b)
print(b.shape)

b = a[:, np.newaxis]
print(b)
print(b.shape)

concatenation

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

b = np.array([[5, 6]])
print(b)

c = np.concatenate((a, b))
print(c)

c = np.concatenate((a, b), axis=None)
print(c)

c = np.concatenate((a, b.T), axis=1)
print(c)

stacking

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)

c = np.hstack((a, b))
print(c)

c = np.vstack((a, b))
print(c)

broadcasting

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])
a = np.array([1, 0, 1])
print(x)
print(a)

y = x + a
print(y)

dot product

In [ ]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
a1 = np.array(l1)
a2 = np.array(l2)

dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

dot = np.dot(a1, a2)
print(dot)

print(np.dot(a1, a2) == a1 @ a2)

speed test array vs list:

In [ ]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a, b)

def dot3():
    return a @ b

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start

start = timer()
for t in range(T):
    dot3()
end = timer()
t3 = end - start

print('list calculation', t1)
print('np.dot', t2)
print('@ dot', t3)
print('ratio list vs np.dot', t1 / t2)
print('ratio list vs @ dot', t1 / t3)
print('ratio np.dot vs @ dot', t2 / t3)

In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(1, 6)
print(a + b)
print(a - b)
print(a * b)  # elementwise product
print(a / b)
print(a ** b)

In [ ]:
print(a + 5)

In [ ]:
a < 30

In [ ]:
A = np.array([[1, 2], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)    # elementwise product
print(A @ B)    # matrix product
print(A.dot(B)) # another matrix product
print(B.dot(A))

Transpose array:

In [ ]:
a = np.array([[1, 2, 6], [3, 4, 8]])
print(a)
print(a.T)

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.diag(a))

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

print(a[a > 2])

print(np.where(a>2, a, -1))

In [ ]:
rg = np.random.default_rng(1)

In [ ]:
a = np.ones((2, 3), dtype=np.int64)
b = rg.random((2, 3))
print(a)
print(b)

In [ ]:
a *= 3
print(a)

In [ ]:
b += a
print(b)

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
print(a.dtype)
print(b.dtype)

In [ ]:
c = a + b
print(c.dtype)

In [ ]:
d = np.exp(c * 1j)
print(d)
print(d.dtype)

In [ ]:
a = rg.random((2, 3))
print(a)

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
b = np.arange(12).reshape((3, 4))
b

In [ ]:
b.sum(axis=0)

In [ ]:
b.sum(axis=1)

In [ ]:
b.max(axis=1)

In [ ]:
b.cumsum(axis=1)

In [ ]:
b.cumprod(axis=1)

In [ ]:
B = np.arange(15)
B

In [ ]:
np.exp(B)

In [ ]:
np.sqrt(B)

In [ ]:
np.all(B)

In [ ]:
np.any(B)

In [ ]:
A = np.array([[5, 3, 1], [3, 8, 1]])

In [ ]:
np.argmax(A)

In [ ]:
np.argmin(A)

In [ ]:
np.argmax(A, axis=1)

In [ ]:
np.argmin(A, axis=1)

In [ ]:
np.argsort(B)

In [ ]:
np.average(B)

In [ ]:
np.bincount(B)

In [ ]:
np.ceil(B)

In [ ]:
np.conj(B)

In [ ]:
np.invert(B)

In [ ]:
np.var(B)

In [ ]:
np.where(B)

In [ ]:
a = np.arange(10)**3
a

In [ ]:
print(a[2])
print(a[2:5])

In [ ]:
a[:6:2] = 1000
a

In [ ]:
a[::-1]

In [ ]:
for i in a:
    print(i ** (1 / 3.))

In [ ]:
np.empty(10)

In [ ]:
np.int32(2**30)

get the numpy version and show numpy build configuration:

In [ ]:
print(np.__version__)
print(np.show_config())

get help on the add function:

In [ ]:
print(np.info(np.add))

test whether none of the elements of a given array is non-zero:

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([0, 2, 4])
print(np.all(x))
print(np.all(y))

test whether any of the elements of a given array is non-zero:

In [ ]:
x = np.array([1, 0, 0, 0])
y = np.array([0, 0, 0])
print(np.any(x))
print(np.any(y))

test a given array element-wise for finiteness (not infinity or not a Number):

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isfinite(x))

test element-wise for positive or negative infinity:

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isinf(x))

test element-wise for NaN of a given array:

In [ ]:
x = np.array([1, 0, np.nan, np.inf])
print(np.isnan(x))

test element-wise for complex number, real number, scalar and non-scalar of a given array:

In [ ]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(x))
print(np.isreal(x))
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

test whether two arrays are element-wise equal within a tolerance:

In [ ]:
x = np.array([3, 5])
y = np.array([2, 5])
print('x =', x)
print('y =', y)
print(np.greater(x, y))
print(np.greater_equal(x, y))
print(np.less(x, y))
print(np.less_equal(x, y))

create an element-wise comparison (equal, equal within a tolerance) of two given arrays:

In [ ]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x, y))
print(np.allclose(x, y))

create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array:

In [ ]:
x = np.array([1, 7, 13, 105], dtype=np.int8)
print(f"{x.size * x.itemsize} bytes")
x = np.array([1, 7, 13, 105], dtype=np.int16)
print(f"{x.size * x.itemsize} bytes")
x = np.array([1, 7, 13, 105], dtype=np.int32)
print(f"{x.size * x.itemsize} bytes")
x = np.array([1, 7, 13, 105], dtype=np.int64)
print(f"{x.size * x.itemsize} bytes")
x = np.array([1, 7, 13, 105], dtype=int)
print(f"{x.size * x.itemsize} bytes")
x = np.array([1, 7, 13, 105])
print(f"{x.size * x.itemsize} bytes")

create an array of the integers from 30 to 70:

In [ ]:
x = np.arange(30, 71)
print(x)

create an array of all the even integers from 30 to 70:

In [ ]:
x = np.arange(30, 71, 2)
print(x)

crete a 3x3 identity matrix:

In [ ]:
x = np.identity(3)
print(x)

generate a random number between 0 and 1:

In [ ]:
x = np.random.normal(0, 1, 1)
print(x)

generate an array of 15 random numbers from a standard normal distribution:

In [ ]:
x = np.random.normal(0, 1, 15)
print(x)

create a vector with values ranging from 15 to 55 and print all values except the first and last:

In [ ]:
x = np.arange(15, 56)
print(x)
print(x[1:-1])

create a 3x4 array using and iterate over it:

In [ ]:
x = np.arange(10, 22).reshape((3, 4))
print(x)
for x in np.nditer(x):
    print(x, end=' ')

create a vector of length 10 with values evenly distributed between 5 and 50:

In [ ]:
x = np.linspace(5, 50, 10, dtype=np.int64)
print(x)

create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15:

In [ ]:
x = np.arange(21)
print(x)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

create a vector of length 20 filled with arbitrary integers from 0 to 10:

In [ ]:
x = np.random.randint(0, 11, 20)
print(x)

multiply the values of two given vectors:

In [ ]:
x = np.array([1, 8, 3, 5])
y = np.random.randint(0, 11, 4)
print(x)
print(y)
print(x * y)

create a 3x4 matrix filled with values from 10 to 21:

In [ ]:
x = np.arange(10, 22).reshape((3, 4))
print(x)

find the number of rows and columns of a given matrix:

In [ ]:
x = np.arange(10, 22).reshape((3, 4))
print(x)
print(x.shape)

create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0:

In [ ]:
x = np.eye(3)
print(x)
x = np.eye(3, 3, k=1)
print(x)

create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0:

In [ ]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

create a 6x6 zero matrix on the main diagonal equal to 1, 2, 3, 4, 5, 6.

In [ ]:
x = np.diag([1, 2, 3, 4, 5, 6])
print(x)

create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal:

In [ ]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

create 3x3x3 array filled with arbitrary values:

In [ ]:
x = np.random.random((3, 3, 3))
print(x)

compute sum of all elements, sum of each column and sum of each row of a given array:

In [ ]:
x = np.array([[0, 1], [2, 3]])
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

compute the inner product of two given vectors:

In [ ]:
x = np.array([4, 5])
y = np.array([7, 10])
print(x)
print(y)
print(np.dot(x, y))

add a vector to each row of a given matrix:

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([1, 1, 0])
print(x)
print(y)
print(np.add(x, y))

save a given array to a binary file:

In [ ]:
x = np.arange(20)
np.save('arr.npy', x)
if os.path.exists('arr.npy'):
    x2 = np.load('arr.npy')
    print(x2)
    print(x)
    print(np.array_equal(x, x2))

save two given arrays into a single file in compressed format (.npz format) and load it:

In [ ]:
x = np.arange(10)
y = np.arange(11, 20)
print(x)
print(y)
np.savez('arr.npz', x=x, y=y)
with np.load('arr.npz') as data:
    print(data['x'])
    print(data['y'])

save a given array to a text file and load it:

In [ ]:
x = np.arange(12).reshape(4, 3)
print(x)
header = 'col1 col2 col3'
np.savetxt('arr.txt', x, fmt='%d', header=header)
r = np.loadtxt('arr.txt')
print(r)

convert a given array into bytes, and load it as array:

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
x_bytes = x.tobytes()
x2 = np.frombuffer(x_bytes, dtype=x.dtype)
print(x2)
print(np.array_equal(x, x2))

convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not:

In [ ]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)
print(a is a2)

compute the x and y coordinates for points on a sine curve and plot the points using matplotlib:

In [ ]:
x = np.arange(0, 6 * np.pi, 0.1)
y = np.sin(x)
print(x)
print(y)
plt.plot(x, y)
plt.show()

convert numpy dtypes to native python types:

In [ ]:
x = np.float64(0)
print(type(x))
pyval = x.item()
print(type(pyval))

add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element:

In [ ]:
def sum_matrix_elements(arr):
    element_sum = 0
    for p in range(len(arr)):
        for q in range(len(arr[p])):
            if arr[p][q] == 0 and p < len(arr) - 1:
                arr[p+1][q] = 0
            element_sum += arr[p][q]
    return element_sum

m = np.array([
    [1, 1, 0, 2],
    [0, 3, 0, 3],
    [1, 0, 4, 4]
])
print(m)
print(sum_matrix_elements(m))

find the missing data in a given array:

In [ ]:
nums = np.array([
    [3, 2, np.nan, 1],
    [10, 12, 10, 9],
    [5, np.nan, 1, np.nan]
])
print(nums)
print(np.isnan(nums))

check two arrays are equal (element wise) or not

In [ ]:
a1 = np.array([0.5, 1.5, 0.2])
a2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print(a1)
print(a2)

print(a1 == a2)
print(np.equal(a1, a2))

create one-dimensional array of single, two and three digits:

In [ ]:
print(np.arange(0, 10))
print(np.arange(10, 100))
print(np.arange(100, 1000))

In [ ]:
print(np.arange(1, 151).reshape((15, 10)))

create a two-dimensional array of numbers from 1 to 150(ten numbers in one sub-array):

In [ ]:
print(np.arange(1, 151).reshape((-1, 10)))

In [ ]:
print(np.arange(1, 151).reshape((15, -1)))

create a one dimensional array of forty pseudo-randomly generated values. Select random numbers from a uniform distribution between 0 and 1:

In [ ]:
print(np.random.rand(40))

create a two-dimensional array with shape (8, 5) of random numbers. Select random numbers from a normal distribution (200, 7)

In [ ]:
print(np.random.normal(200, 7, (8, 5)))

generate a uniform, non-uniform random sample from a given 1-D array with and without replacement:

In [ ]:
print(np.random.choice(7, 5))
print(np.random.choice(7, 5, replace=False))

print(np.random.choice(7, 5, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))
print(np.random.choice(7, 5, replace=False, p=[0.1, 0.2, 0, 0.2, 0.4, 0, 0.1]))

create a 4x4 array with random values, now create a new array from the said array swapping first and last rows:

In [ ]:
a = np.arange(16, dtype='int').reshape((-1, 4))
print(a)

a[[0,-1], :] = a[[-1,0], :]
print(a)

create a 4x4 array with random values, now create a new array from the said array swapping first and last, second and third columns:

In [ ]:
a = np.arange(16, dtype='int').reshape((-1, 4))
print(a)

print(a[:, ::-1])

create a new array of given shape (5, 6) and type, filled with zeros:

In [ ]:
a = np.zeros(shape=(5, 6), dtype='int')
print(a)

a[::2, ::2] = 3
a[1::2, ::2] = 7
print(a)

sort a given array by row and column is ascending order:

In [ ]:
a = np.array([
    [5.54, 3.38, 7.99],
    [3.54, 4.38, 6.99],
    [1.54, 2.39, 9.29]
])
print(a)

print(np.sort(a))
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

extract all numbers from a given array which are less and greater than a specified number:

In [ ]:
a = np.array([
    [5.54, 3.38, 7.99],
    [3.54, 4.38, 6.99],
    [1.54, 2.39, 9.29]
])
print(a)

print(a[a > 5])
print(a[a < 4])

replace all numbers if a given array which is equal, less and greater to a given number:

In [ ]:
a = np.array([
    [5, 3, 7],
    [3, 4, 6],
    [1, 2, 9],
])
print(a)
n = 3
r = 10
print(np.where(a == n, r, a))
print(np.where(a < n, r, a))
print(np.where(a > n, r, a))

create an array of equal shape and data type of given array:

In [ ]:
a = np.array([
    [5, 3, 7],
    [3, 4, 6],
    [1, 2, 9],
])
print(a)
print(np.zeros_like(a))

create a tree-dimension array with shape (3, 5, 4) and set to a variable:

In [ ]:
a = np.array([
    [
        [1, 5, 2, 1],
        [4, 3, 5, 6],
        [6, 3, 0, 6],
        [7, 3, 5, 0],
        [2, 3, 3, 5],
    ],
    [
        [2, 2, 3, 1],
        [4, 0, 0, 5],
        [6, 3, 2, 1],
        [5, 1, 0, 0],
        [0, 1, 9, 1],
    ],
    [
        [3, 1, 4, 2],
        [4, 1, 6, 0],
        [1, 2, 0, 6],
        [8, 3, 4, 0],
        [2, 0, 2, 8],
    ]
])

print(a)

swap rows and columns of a given array in reverse order:

In [ ]:
a = np.array([
    [
        [1, 2, 3, 4],
        [0, 1, 3, 4],
        [90, 91, 93, 94],
        [5, 0, 3, 2]
    ]
])
print(a)

print(a[::-1, ::-1])

multiply two given arrays of same size elements-by-element:

In [ ]:
x = np.array([
    [1, 2, 3],
    [9, 8, 7],
])
y = np.array([
    [4, 6, 2],
    [3, 5, 3],
])
print(x)
print(y)

print(np.multiply(x, y))
print(x * y)